kargo:
  externalWebhooksServer:
    enabled: false
  webhooksServer:
    enabled: false
  api:
    cabundle:
      configMapName: ca
    oidc:
      enabled: true
      issuerURL: https://auth-127-0-0-1.nip.io
      clientID: kargo
      clientSecret: insecure_secret
      dex:
        enabled: false
      admins:
        claims:
          groups:
          - admins
    host: kargo-127-0-0-1.nip.io
    adminAccount: 
      enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: ca-issuer
      tls:
        enabled: true
        selfSignedCert: false 
  controller:
    cabundle:
      configMapName: ca
    globalCredentials:
      namespaces: orchestration
    argocd:
      namespace: orchestration