kargo: 
  api:
    oidc: 
      enabled: true
      issuerURL: https://auth.localhost/realms/gluki
      clientID: kargo
      dex:
        enabled: false
      admins:
        claims:
          groups:
          - admins
    host: kargo.localhost
    adminAccount: 
      enabled: false
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: nginx
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: selfsigned
      tls:
        enabled: true
        selfSignedCert: false 
  controller:
    globalCredentials:
      namespaces: orchestration
    argocd:
      namespace: orchestration